import clsx from "clsx";

export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className={clsx("flex")}>
      <div className={clsx("bg-black w-2/5 h-screen")}>

      </div>
      <div className={clsx("bg-white w-3/5 h-full")}>{children}</div>
    </div>
  )
}
