//import from individual
import clsx from "clsx";
import "./styles.scss";

// import from next
import Image from "next/image";
export const metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className={clsx("flex")}>
      <div className="relative w-2/5 h-screen max-vs:hidden">
        <div className="absolute inset-0 bg-[url('/image/background-image.webp')] bg-cover bg-center"></div>

        <div className="absolute inset-0 bg-gradient-to-r from-[rgba(70,174,252,0.9)] to-[rgba(70,174,252,0.9)]"></div>

        <div className="absolute top-[190px] z-10 text-white p-8">
          <div
            className={clsx(
              "flex justify-between items-center w-[115px] text-black font-black text-xl mb-5"
            )}
          >
            <Image src={"/image/logo.png"} alt="Logo" width={40} height={31} />

            <span>MovieTicket</span>
          </div>
          <h1 className={clsx("font-bold mb-5 text-3xl", "title-text")}>
            Welcome to MovieTicket
          </h1>
          <p
            className={clsx(
              "text-base tracking-wider text-justify",
              "detail-text"
            )}
          >
            Hệ thống cho phép bạn lựa chọn suất chiếu, rạp phim yêu thích và ghế
            ngồi chỉ với vài thao tác đơn giản. Ngoài ra, bạn còn có thể cập
            nhật các bộ phim mới nhất, đọc nhận xét từ cộng đồng và chia sẻ ý
            kiến của mình về các tác phẩm điện ảnh. Trải nghiệm đặt vé chưa bao
            giờ dễ dàng và thú vị đến thế
          </p>
        </div>
      </div>
      <div className={clsx("bg-white w-3/5 h-screen max-vs:w-full")}>
        {children}
      </div>
    </div>
  );
}
