server:
  port: 8080
  tomcat:
    threads:
      max: 200
  servlet:
    context-path: /api/v1

spring:
  application:
    name: movie-ticket-booking
  datasource:
    hikari:
      maximum-pool-size: 20 # Số lượng tối đa kết nối
      minimum-idle: 5 # Số lượng kết nối tối thiểu trong pool
    url: jdbc:postgresql://localhost:5555/movie-ticket-booking
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      indent-output: true

  # Redis Connection settings
  data:
    redis:
      host: 127.0.0.1
      port: 6666
      password: secret
      lettuce:
        pool: #Connection pool settings
          max-active: 8 #Maximum number of active connections in the pool (uses -1 for no limit)
          max-idle: 8 #Maxmimum number of idle connections in the pool
          min-idle: 0 # Minimum number of idle connections in the pool
          max-wait: -1ms #Maximum wait time to get a connection from the pool (-1 for no limit)
      connect-timeout: 30000 #Connection timeout (in milliseconds)

minio:
  endpoint: http://127.0.0.1:9000
  access-key: DDTB8XJEcBivsq5y8MiK
  secret-key: pxav5ZPO08jCHHQuK3ij2rnpC0tcHUNOt7bI1P30