export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <>
      <div className="py-4">{children}</div>
    </>
  );
}
