//import from individual
import "./styles.scss";
export const metadata = {
  title: "Detail Movie",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background">
      {children}
    </div>
  );
}
